### ISSUE TITLE
Can ping but netscan reports offline

### ISSUE THREAD

**Issue by HansSchoe** [AdyRock/homey-netscan#13]
I have some strange behavior. on win11 pc.
If I disable the firewall netscan works fine.
If I enable the firewall netscan reports offline but ping works fine. (activated the icmp rules)
So it must be a setting in the firewall.
Any ideas what setting? I did all the icmp rules

**Comment by AdyRock** [comment]
The app can't use ping as that requires permissions that are not available to an app.
All I can suggest is try and find a port that is in use by the pc and use that in the app.

**Comment by HansSchoe** [comment]
Thx for reply, but no luck.

**Comment by HansSchoe** [comment]
Solved it by pinging from Home Assistant and then use the ha integration.
