### ISSUE TITLE
Question: What port is checked with the IP only?

### ISSUE THREAD

**Issue by jrhansen** [AdyRock/homey-netscan#2]
What port is the app checking, when entering an IP address only with the "IP address" device? Does it ping the IP instead or...?

**Comment by AdyRock** [comment]
It checks on port 1. It assumes the port is closed but should get a rejection if the device is online. If the device is switched off then the request will timeout. However sometimes firewalls can block any response from being sent. 
Unfortunately I can't use a ping as that requires system privileges that are not available to apps.

**Comment by jrhansen** [comment]
Apparently, the router in the other end does not respond to request on closed ports (such as port 1), which explains why I could not get it to work.

I now have it set up to check access to routers in two other houses - effectively monitoring for power outages.

Thanks, AdyRock, for the response - and thanks for spending time maintaining this!
