### ISSUE TITLE
Everything I add is off-line

### ISSUE THREAD

**Issue by hummelmose** [AdyRock/homey-netscan#3]
I run Homey 7.2.1, and have just installed Net Scan 2.0.4.

No matter what I add on internal ip's it tells me the state is off-line. Both on IP and Port scan.

I can ping, and i can port scan with other tools that finds them fine :-)
![Snag_1b2efdf](https://user-images.githubusercontent.com/8464889/150142938-53cc66a9-22c2-4745-a87b-947d15b7bd5f.png)

Keep up the good work.

**Comment by AdyRock** [comment]
Could you open the Configure App screen or go to https://tools.developer.homey.app/tools/app-settings and select the NetScan app then set the log level to Basic Information.

After it has scanned for a few minutes could you click on send to email the log to me.

**Comment by hummelmose** [comment]
Just sent log  :-) (y)

**Comment by AdyRock** [comment]
Hmm, that doesn't look right, it shows they are still online. I will investigate.

**Comment by hummelmose** [comment]
If you need me to check anything please let me know - I have homeyscript installed, so if you need me to do some digging how the Homey Pro is responting to ping against the IP's I can try :-)

**Comment by AdyRock** [comment]
Ah ha, Sorry it is bad wording for the capability and it caught me out then :-)
The "Device Offline" is the title of the capability but the state is false (grey circle). If the device was offline then the circle would be red.
In my defence I pick the app up from another developer and just brought it up to date but kept the original functionality for backward compatibility.

**Comment by hummelmose** [comment]
OK - Could we have a green circle if it's OK and red if not :-) - And then maybe call it Device Status in stead - Thanks a mill for rapid answer.

**Comment by hummelmose** [comment]
![image](https://user-images.githubusercontent.com/8464889/150147345-4b81b173-469a-427a-a80b-a9bd146e084f.png)

I would allways guess this to be offline :-)

**Comment by AdyRock** [comment]
Unfortunately the circle colour is fixed by Athom so I can't change that. All I can do is set the state to true or false.
Hmm, well it does say Device Offline: No ;-)
I will have a look at the wording and try to make it clearer.

**Comment by hummelmose** [comment]
Thanks a mill - A suggestion

Device Online - YES / NO

**Comment by AdyRock** [comment]
Same thing really but I would have to reverse all the logic and make sure it doesn't break everyone's existing flows.

**Comment by hummelmose** [comment]
don't do it then :-) thanks for answering.

**Comment by AdyRock** [comment]
It looks more obvious when it does go offline:
![image](https://user-images.githubusercontent.com/38184396/150149107-44438f76-77a4-4744-9dc4-fb6010cd04ba.png)
![image](https://user-images.githubusercontent.com/38184396/150149208-2af8eb18-a361-41f4-a300-873eaf633b8a.png)
And the second image the icon is pulsating red.

**Comment by hummelmose** [comment]
![image](https://user-images.githubusercontent.com/8464889/150149857-bf071e38-551f-49fc-a7be-f13bc0d5b4c5.png)

I see - Thanks for answering 👍

**Comment by hummelmose** [comment]
I will close the issue
