### ISSUE TITLE
Not working on 2023 Homey?

### ISSUE THREAD

**Issue by malmentm** [AdyRock/homey-netscan#7]
Hello, I cannot get this to work on 2023 Homey. It always says ip not reachable even though I know it is. Any ideas?

**Comment by 4braincells** [comment]
Hi, 
app is installed and visible in settings, 
but not when adding logic , neither standard nor advanced flow.

**Comment by AdyRock** [comment]
Have you added devices to monitor?

**Comment by hubocan** [comment]
What is the intended use of "IP Address"? I have a Windows Server and it says that the device is offline, but I can ping the server without problem. In case of use of the "TCP Port" and set it to 80, it works.

**Comment by AdyRock** [comment]
"IP address" tries to connect to port 1 and only shows offline if there is no response. This is the original app's device, but as not all devices will respond  the ne method was added so you can specify a port to test. However, there has to be a "valid" response to determine the device is online. 

Ideally I would like to ping a device but apps don't get access to that system function.

**Comment by groetsels** [comment]
Ik wil deze app gebruiken om online status te bepalen.
Een ping naar 8.8.8.8 (google dns) zou een mooie optie zijn, maar de app geeft altijd offline.
Heb je eeen suggestie welk ip adres ik kan gebruiken om status online te bepalen?

**Comment by hubocan** [comment]
> Ik wil deze app gebruiken om online status te bepalen. Een ping naar 8.8.8.8 (google dns) zou een mooie optie zijn, maar de app geeft altijd offline. Heb je eeen suggestie welk ip adres ik kan gebruiken om status online te bepalen?
> 
> 10:13:17.379: * Checking IP device google dns - 8.8.8.8 10:13:27.399: * Device Timeout google dns - 8.8.8.8 10:13:27.400: * Device still Offline google dns - 8.8.8.8 10:13:27.401: * google dns - 8.8.8.8 on close

Any web address with port 80/443... i.e. get IP of google.com and use port 80.

**Comment by hubocan** [comment]
BTW I think this issue can be closed.

**Comment by AdyRock** [comment]
Closing this issue if no one objects
